---
apiVersion: v1
kind: ConfigMap
metadata:
  name: image-commands
data:
  build_image: |
    #!/bin/sh
    CONTAINERFILE="Dockerfile"
    if [ -f Containerfile ]; then
      CONTAINERFILE="Containerfile"
    fi
    executor --registry-certificate registry:5000=/certs/tls.crt --destination=registry:5000${PWD}:latest --force -f ${CONTAINERFILE} --cache=true --cache-dir=/cache
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: debug
spec:
  serviceName: debug
  selector:
      matchLabels:
        app: debug
  template:
    metadata:
      labels:
        app: debug
    spec:
      containers:
      - name: debug
        image: fedora:35
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      - name: build
        image: gcr.io/kaniko-project/executor:v1.7.0-debug
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: certs
          mountPath: /certs
        - name: bin
          mountPath: /usr/local/bin/
        - name: cache
          mountPath: /cache
      terminationGracePeriodSeconds: 3
      volumes:
      - name: bin
        configMap:
          defaultMode: 0755
          name: image-commands
      - name: cache
        emptyDir: {}
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace
      - name: certs
        secret:
          secretName: registry-tls
