resources:
- "../../develop/"
commonLabels:
  app: go-prototype
patches:
- target:
    name: develop
  patch: |-
    - op: replace
      path: /metadata/name
      value: go-prototype
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: develop
  spec:
    template:
      spec:
        securityContext:
          runAsUser: 0
        containers:
        - name: main
          image: mcr.microsoft.com/devcontainers/go:1-1.21-bookworm
          env:
          - name: INSTALL_PACKAGES
            value: "git less zsh bash protobuf-compiler"
          - name: GOROOT
            value: "/usr/local/go"
          - name: GOPATH
            value: "${HOME}/go:/go"
          - name: CHECKOUT_PROJECT
            value: "https://github.com/grpc/grpc-go"
          - name: PROJECT_DIR
            value: "$HOME/src/grpc-go"
