resources:
- "../../develop/"
commonLabels:
  app: go-prototype
patches:
- target:
    name: develop
  patch: |-
    - op: replace
      path: /metadata/name
      value: go-prototype
configMapGenerator:
- name: user-home
  behavior: merge
  files:
  - "home/.project_profile"
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: develop
  spec:
    template:
      spec:
        containers:
        - name: main
          image: golang:1.19
