---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: develop
spec:
  storageClassName: persistent-workspace
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: develop
spec:
  template:
    spec:
      containers:
      - name: main
        image: registry:5000/maintenance
