apiVersion: apps/v1
kind: Deployment
metadata:
  name: develop
spec:
  template:
    spec:
      initContainers:
      - name: init-backup
        image: ghcr.io/naviator/backup
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: BACKUP_REMOTE
          value: "backup/$(POD_NAMESPACE)/$(APP_NAME)"
        - name: BACKUP_BORG_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devtemplate.naviator.github.io/backup-borg-service']
        command:
        - /bin/sh
        - -c
        args:
        - |
          cd /data
          sh /opt/backup/extract.sh
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: backup
        image: ghcr.io/naviator/backup
        env:
        - name: BACKUP_INTERVAL
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devtemplate.naviator.github.io/backup-interval']
        - name: BACKUP_DELAY
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devtemplate.naviator.github.io/backup-delay']
        - name: BACKUP_BORG_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devtemplate.naviator.github.io/backup-borg-service']
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: BACKUP_REMOTE
          value: "backup/$(POD_NAMESPACE)/$(APP_NAME)"
        resources:
          requests:
            memory: 20Mi
            cpu: 10m
          limits:
            memory: 100Mi
            cpu: 2000m
        volumeMounts:
        - name: data
          mountPath: /data
        command:
        - /bin/sh
        - -c
        args:
        - |
          set -eux

          sleep ${BACKUP_DELAY}
          while true; do
            cd /data
            sh /opt/backup/create.sh
            sleep ${BACKUP_INTERVAL}
          done
