resources:
- "../../develop/"
commonLabels:
  app: rust-prototype
patches:
- target:
    name: develop
  patch: |-
    - op: replace
      path: /metadata/name
      value: rust-prototype
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: develop
  spec:
    template:
      spec:
        securityContext:
          runAsUser: 0
        containers:
        - name: main
          image: quay.io/instrumentisto/rust:1.68.2-buster
          env:
          - name: INSTALL_PACKAGES
            value: "git less zsh capnproto libcapnp-dev"
          - name: CHECKOUT_PROJECT
            value: "https://github.com/capnproto/capnproto-rust.git"
          - name: PROJECT_DIR
            value: "$HOME/src/capn"
            # remove number of jobs to remove limit
          - name: CARGO_BUILD_JOBS
            value: "8"
