FROM alpine

RUN apk add --update --no-cache \
    openssh-server \
    # newer nsenter
    util-linux \
    # useful for file transfer
    rsync \
    # client is useful for debugging & rsync
    openssh-client \
    # useful for Kubernetes API & other stuff
    curl

ENV USER=dev UID=3000

RUN echo "Adding user: ${USER} (${UID})"; \
    adduser --disabled-password --uid ${UID} --shell /bin/sh \
    --home /data ${USER} && \
    sed -i "s/${USER}:!/${USER}:*/g" /etc/shadow

# no need for motto of the day
RUN rm /etc/motd

COPY --chmod=644 sshd_config /etc/ssh/sshd_config
COPY entrypoint.sh /

USER 3000
EXPOSE 2222/tcp
VOLUME "/data"

ENTRYPOINT [ "/entrypoint.sh" ]
