FROM alpine

RUN apk add --update --no-cache \
    openssh-server \
    # newer nsenter
    util-linux \
    # useful for file transfers
    rsync \
    # client is useful for debugging & rsync
    openssh-client \
    # useful for Kubernetes API & other stuff
    curl \
    # backup with versioning
    borgbackup socat

ARG USER=dev
ARG UID=30001

RUN echo "Adding user: ${USER} (${UID})"; \
    adduser --disabled-password --uid ${UID} --shell /bin/sh ${USER} && \
    sed -i "s/${USER}:!/${USER}:*/g" /etc/shadow

# no need for motto of the day
RUN rm /etc/motd

# keeping original /etc/ssh/sshd_config for documentation
COPY --chmod=644 sshd_config /etc/ssh/sshd_config_template
COPY entrypoint.sh /

USER dev

EXPOSE 2222/tcp

ENTRYPOINT [ "/entrypoint.sh" ]
