---
apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-script
data:
  setup.sh: |
    #!/bin/bash

    set -eux

    sed -i 's/127.0.0.1[[:blank:]]*localhost/127.0.0.1 registry localhost/g' /etc/hosts
    if [ -d "/usr/local/share/ca-certificates/" ]; then
      echo "$TRUSTED_CERT" > /usr/local/share/ca-certificates/registry.crt
      update-ca-certificates
      systemctl restart k3s.service
    elif [ -d "/etc/pki/ca-trust/source/anchors/" ]; then
      echo "$TRUSTED_CERT" > /etc/pki/ca-trust/source/anchors/registry.crt
      update-ca-trust
      systemctl restart k3s.service
    else
      echo "Cannot install certificate"
      exit 1
    fi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-custom-setup
  labels:
    k8s-app: node-custom-setup
spec:
  selector:
    matchLabels:
      k8s-app: node-custom-setup
  template:
    metadata:
      labels:
        k8s-app: node-custom-setup
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: init
        command: ["nsenter"]
        args: ["--mount=/proc/1/ns/mnt", "--", "sh", "-c", "$(SETUP_SCRIPT)"]
        image: debian
        env:
        - name: TRUSTED_CERT
          valueFrom:
            secretKeyRef:
              name: registry-tls
              key: tls.crt
        - name: SETUP_SCRIPT
          valueFrom:
            configMapKeyRef:
              name: setup-script
              key: setup.sh
        securityContext:
          privileged: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  selector:
      matchLabels:
        app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - image: registry:2.8.1
          name: registry
          resources:
            requests:
              memory: "100Mi"
              cpu: "1m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
          - name: REGISTRY_HTTP_ADDR
            value: 0.0.0.0:5001
          - name: REGISTRY_HTTP_PREFIX
            value: /
          - name: REGISTRY_HTTP_HOST
            value: https://registry:5001
          - name: REGISTRY_HTTP_TLS_CERTIFICATE
            value: "/certs/tls.crt"
          - name: REGISTRY_HTTP_TLS_KEY
            value: "/certs/tls.key"
          ports:
          - containerPort: 5001
            protocol: TCP
            name: web
          volumeMounts:
          - name: registry
            mountPath: /var/lib/registry
          - name: certs
            mountPath: /certs
            readOnly: true
      volumes:
      - name: registry
        hostPath:
          path: /data/registry
          type: DirectoryOrCreate
      - name: certs
        secret:
          secretName: registry-tls
---
kind: Service
apiVersion: v1
metadata:
  name: registry
spec:
  type: LoadBalancer
  selector:
    app: registry
  ports:
  - name: web
    port: 80
    targetPort: web
  - name: web2
    port: 5001
    targetPort: web
