---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: develop
  labels:
    app: develop
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: develop
      naviator.github.com/devtemplate: deployment
  template:
    metadata:
      labels:
        app: develop
        naviator.github.com/devtemplate: deployment
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: init
        image: ghcr.io/naviator/bastion
        env:
        - name: APP_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        command:
        - /bin/sh
        - -c
        args:
        - 
          echo "Construct home...";
          rsync -rLv /usr/home/ /data;
          mkdir -m 700 -p /data/.ssh;
          echo $(id -u):$(id -g) > /tmp/.runas;
          cp /usr/ssh/authorized_keys /data/.ssh/authorized_keys;
          echo "Init done...";
        volumeMounts:
        - name: data
          subPathExpr: home
          mountPath: /data
        - name: data
          subPathExpr: workspace
          mountPath: /workspace
        - name: user-ssh
          mountPath: /usr/ssh
        - name: user-home
          mountPath: /usr/home
        - name: tmp
          mountPath: /tmp
        securityContext:
          privileged: true
      containers:
      - name: gate
        image: ghcr.io/naviator/bastion
        env:
        - name: AUTHORIZED_KEYS_PATH
          value: /usr/ssh/authorized_keys
        - name: SSHD_CONFIG_PATH
          value: /usr/ssh/sshd_config
        - name: HOME
          value: "/root"
        - name: USER
          value: "root"
        - name: TARGET_SHELL
          value: zsh
        ports:
        - name: ssh
          containerPort: 2222
        volumeMounts:
          # sharing /tmp because auth_sock_dir was hardcoded
          # https://github.com/openssh/libopenssh/blob/011c12f6898fba5c6f84c287ed39c16efa006012/ssh/session.c#L179
        - name: tmp
          mountPath: /tmp
        - name: user-ssh
          mountPath: /usr/ssh
        - name: devscripts
          mountPath: /devscripts
        - name: visit-target
          subPath: visit_target.sh
          mountPath: /etc/profile
        resources:
          requests:
            memory: 1Mi
            cpu: 1m
          limits:
            memory: 1Gi
            cpu: 2000m
        securityContext:
          runAsUser: 0
          # TODO reduce privileged to required nsenter capabilites
          privileged: true
        startupProbe:
          tcpSocket:
            port: ssh
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 3
      - name: main
        image: ghcr.io/naviator/bastion
        stdin: true
        tty: true
        env:
        - name: APP_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        command:
        - /bin/sh
        - -c
        args:
        - 
          sh /devscripts/provision_machine.sh &&
          sh /devscripts/provision_user.sh &&
          sh /devscripts/entrypoint.sh 
        securityContext:
          runAsUser: 0
          privileged: true
        startupProbe:
          exec:
            command:
            - cat
            - /tmp/.started
          failureThreshold: 30
          periodSeconds: 10
        volumeMounts:
        - name: data
          subPathExpr: home
          mountPath: /data
        - name: data
          subPathExpr: workspace
          mountPath: /workspace
        - name: tmp
          mountPath: /tmp
        - name: devscripts
          mountPath: /devscripts
        resources:
          requests:
            cpu: 1m
            memory: 10Mi
          limits:
            cpu: 6000m
            memory: 8Gi
      serviceAccountName: dev
      terminationGracePeriodSeconds: 1
      volumes:
      - name: devscripts
        configMap:
          name: devscripts
          defaultMode: 0755
      - name:  visit-target
        configMap:
          name: visit-target
          defaultMode: 0755
      - name: data
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: user-ssh
        secret:
          secretName: user-ssh
          optional: false
          defaultMode: 0600
      - name: user-home
        configMap:
          name: user-home
          defaultMode: 0600
