---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: develop
  labels:
    app: develop
  annotations:
    devtemplate.naviator.github.io/backup: "borg"
    # devtemplate.naviator.github.io/backup-snapshot: "btrfs"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: develop
      devtemplate.naviator.github.io/role: develop
  template:
    metadata:
      labels:
        app: develop
        devtemplate.naviator.github.io/role: develop
      annotations:
        # backup config (if backup is applied)
        devtemplate.naviator.github.io/backup-delay: "10m"
        devtemplate.naviator.github.io/backup-interval: "5m"
        devtemplate.naviator.github.io/backup-borg-service: "storage:7777"
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      serviceAccountName: dev
      terminationGracePeriodSeconds: 5
      volumes:
      - name: devscripts
        configMap:
          name: devscripts
          defaultMode: 0755
      - name:  visit-target
        configMap:
          name: visit-target
          defaultMode: 0755
      - name: data
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: user-home
        configMap:
          name: user-home
          defaultMode: 0600
      initContainers:
      # store desired UID:GID for pod
      - name: init-uid
        image: ghcr.io/naviator/backup
        command:
        - /bin/sh
        - -c
        args:
        - echo $(id -u):$(id -g) > /tmp/.runas
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      containers:
      - name: main
        image: ghcr.io/naviator/bastion
        # develop images can be rarther large
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        lifecycle:
          postStart:
            exec:
              # installation usually does not have to be blocking
              command: ["/bin/sh", "-c", "sh /devscripts/provisioning.sh install"]
        env:
        - name: APP_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app']
        command:
        - /bin/sh
        - -c
        args:
        - 
          sh /devscripts/provisioning.sh sudo &&
          sh /devscripts/entrypoint.sh
        securityContext:
          runAsUser: 0
        startupProbe:
          exec:
            command:
            - cat
            - /tmp/.pid
          failureThreshold: 30
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        - name: devscripts
          mountPath: /devscripts
        - name: user-home
          mountPath: /default-volume/data
        resources:
          limits:
            cpu: 12000m
            memory: 10Gi
          requests:
            cpu: 500m
            memory: 200Mi
      - name: gate
        image: ghcr.io/naviator/bastion
        env:
        - name: TARGET_SHELL
          # Remote SSH extension requires bash when sh/zsh just won't do
          value: bash
        - name: SSH_AUTHORIZED_KEYS
          valueFrom:
            secretKeyRef:
              name: user-ssh
              key: authorized_keys
              optional: false
        ports:
        - name: ssh
          containerPort: 2222
        volumeMounts:
          # sharing /tmp because auth_sock_dir was hardcoded
          # https://github.com/openssh/libopenssh/blob/011c12f6898fba5c6f84c287ed39c16efa006012/ssh/session.c#L179
        - name: tmp
          mountPath: /tmp
        - name: devscripts
          mountPath: /devscripts
        - name: visit-target
          subPath: visit_target.sh
          # some IDEs invoke of "bash" without login ("-l")
          # could otherwise be:
          mountPath: /etc/profile
          # mountPath: /bin/bash
        resources:
          limits:
            memory: 200Mi
            cpu: 1000m
          requests:
            memory: 10Mi
            cpu: 10m
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_PTRACE
        startupProbe:
          tcpSocket:
            port: ssh
          failureThreshold: 30
          periodSeconds: 10
          initialDelaySeconds: 3
