resources:
- deployment.yaml
- service.yaml
patches:
- path: backup/borg.yaml
  target:
    annotationSelector: "devtemplate.naviator.github.io/backup=borg"
- path: backup/borg-btrfs.yaml
  target:
    annotationSelector: "devtemplate.naviator.github.io/backup-snapshot=btrfs"
- path: backup/borg-btrfs-encrypted.yaml
  target:
    annotationSelector: "devtemplate.naviator.github.io/backup-snapshot=btrfs-encrypted"
