---
apiVersion: v1
kind: Service
metadata:
  name: develop
spec:
  type: ClusterIP
  selector:
    app: develop
    devtemplate.naviator.github.io/role: develop
  ports:
  - name: ssh
    port: 2222
    targetPort: ssh
