apiVersion: v1
kind: Pod
metadata:
  name: go
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: dev
    command:
    - sleep
    - infinity
    image: golang:1.17-bullseye
    env:
    - name: GOROOT
      value: /usr/local/go
    - name: PATH
      value: "/usr/local/go/bin/:/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 500Mi
        cpu: 2000m
    volumeMounts:
    - mountPath: /workspace
      name: workspace
  restartPolicy: Always
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: workspace
