---
apiVersion: v1
kind: Service
metadata:
  name: app-dev
spec:
  type: ClusterIP
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
    name: ssh
  selector:
    app: app-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
  labels:
    app: app-dev
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-dev
  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
      - name: dev
        command:
        - /bin/bash
        - -c
        args:
        -
          env > /tmp/env;
          /usr/local/devscripts/dev_init.sh
        ports:
        - containerPort: 22
        image: golang:1.17-bullseye
        env:
        - name: GOROOT
          value: /usr/local/go
        - name: PATH
          value: "/usr/local/go/bin/:/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        livenessProbe: null
        resources:
          requests:
            memory: 100Mi
            cpu: 10m
          limits:
            memory: 500Mi
            cpu: 2000m
        volumeMounts:
        - mountPath: /workspace
          name: workspace
        - mountPath: /usr/local/devscripts
          name: devscripts
          readOnly: true
        - mountPath: /var/run/secrets/user-ssh
          name: user-ssh
        securityContext:
          runAsGroup: 0
          runAsUser: 0
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      restartPolicy: Always
      serviceAccountName: dev
      terminationGracePeriodSeconds: 1
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace
      - name: devscripts
        configMap:
          name: devscripts
          defaultMode: 0755
      - name: user-ssh
        secret:
          secretName: user-ssh
          defaultMode: 0600
