apiVersion: v1
kind: Pod
metadata:
  name: python
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: dev
    command:
    - sleep
    - infinity
    image: python:3.8-bullseye
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 500Mi
        cpu: 2000m
    volumeMounts:
    - mountPath: /workspace
      name: workspace
  restartPolicy: Always
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: workspace
