---
# Source: redpanda/charts/console/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redpanda-console
  labels:
    helm.sh/chart: console-0.5.6
    app.kubernetes.io/name: console
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: "v2.2.0"
    app.kubernetes.io/managed-by: Helm
