apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
  labels:
    naviator.github.io/devtemplate: bastion
spec:
  selector:
    matchLabels:
      naviator.github.io/devtemplate: bastion
  template:
    metadata:
      labels:
        naviator.github.io/devtemplate: bastion
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: main
        image: ghcr.io/naviator/bastion
        env:
        - name: SSH_AUTHORIZED_KEYS
          valueFrom:
            secretKeyRef:
              name: user-ssh
              key: authorized_keys
              optional: false
        ports:
        - name: ssh
          containerPort: 2222
        resources:
          limits:
            memory: 1Gi
            cpu: 2000m
          requests:
            memory: 1Mi
            cpu: 1m
---
apiVersion: v1
kind: Service
metadata:
  name: bastion
spec:
  selector:
    naviator.github.io/devtemplate: bastion
  ports:
  - port: 2222
    targetPort: ssh
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bastion-egress
spec:
  podSelector:
    matchLabels:
      naviator.github.io/devtemplate: bastion
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 2222
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
