apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
  labels:
    app: bastion
spec:
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: main
        image: ghcr.io/naviator/bastion
        env:
        - name: AUTHORIZED_KEYS_PATH
          value: /usr/ssh/authorized_keys
        - name: SSHD_CONFIG_PATH
          value: /usr/ssh/sshd_config
        ports:
        - name: ssh
          containerPort: 2222
        volumeMounts:
        - name: user-ssh
          mountPath: /usr/ssh
        resources:
          limits:
            memory: 1Gi
            cpu: 2000m
          requests:
            memory: 1Mi
            cpu: 1m
      volumes:
      - name: user-ssh
        secret:
          secretName: user-ssh
          optional: false
          defaultMode: 0644
---
apiVersion: v1
kind: Service
metadata:
  name: bastion
spec:
  selector:
    app: bastion
  ports:
  - port: 22
    targetPort: ssh
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bastion-egress
spec:
  podSelector:
    matchLabels:
      app: bastion
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 2222
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
