resources:
- "ssh"
- "bastion.yaml"
- "storage.yaml"
- "service_account.yaml"
configMapGenerator:
- name: devscripts
  files:
  - "devscripts/provisioning.sh"
  - "devscripts/entrypoint.sh"
- name: user-home
  files:
  - "home/.bashrc"
  - "home/.zshrc"
  - "home/.profile"
  - "home/.p10k.zsh"
  - "home/.gitconfig"
- name: visit-target
  files:
  - "visit_target.sh"
generatorOptions:
  disableNameSuffixHash: true
