---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev
roleRef:
  kind: Role
  name: dev
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: dev
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: develop-permissive
spec:
  podSelector:
    matchLabels:
      dev: enabled
  egress:
  - {}
  policyTypes:
  - Egress
