---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace
spec:
  storageClassName: manual
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/workspace"
    type: DirectoryOrCreate
