FROM alpine

RUN apk add --update --no-cache \
    # backup with versioning
    borgbackup socat \
    # snapshot
    btrfs-progs sudo \
    # encryption
    cryptsetup \
    # useful for Kubernetes API & other stuff
    curl jq

ARG USER=backup
ARG UID=30002

RUN echo "Adding user: ${USER} (${UID})"; \
    adduser --disabled-password --uid ${UID} --shell /bin/sh ${USER} && \
    sed -i "s/${USER}:!/${USER}:*/g" /etc/shadow

# no need for motto of the day
RUN rm /etc/motd

ENV BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK="yes" \
    BORG_BASE_DIR="/tmp/borg" \
    # define USERNAME avoiding KeyError: 'getpwuid(): uid not found: ...' getpass.py: getuser()
    USERNAME="backup"

RUN mkdir -p /opt/backup

COPY create.sh extract.sh /opt/backup/

ENV BACKUP_DELAY="10m" \
    BACKUP_INTERVAL="5m" \
    BACKUP_REMOTE="/backup" \
    BACKUP_BORG_SERVICE="storage:7777"

USER backup
EXPOSE 7777/tcp
VOLUME [ "/backup" ]

ENTRYPOINT [ "/bin/sh", "-c" ]

CMD [ "socat TCP-LISTEN:7777,fork EXEC:'borg serve --restrict-to-path /backup'" ]
