name: GitHub Actions Demo
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Bastion Image
      uses: redhat-actions/buildah-build@v2
      id: build-image
      with:
        image: ghcr.io/${{ github.actor }}/bastion
        context: ./image/bastion/
        platforms: linux/amd64, linux/arm, linux/arm64
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./image/bastion/Containerfile

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push Image
      id: push-image
      uses: redhat-actions/push-to-registry@v2.6
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-image.outputs.registry-paths }}"
