resources:
- "../../develop/"
commonLabels:
  app: go
patches:
- target:
    name: develop
  patch: |-
    - op: replace
      path: /metadata/name
      value: go
configMapGenerator:
- name: user-home
  behavior: merge
  files:
  - "home/.project_profile"
patchesStrategicMerge:
- patch.yaml
